import type { MasterSnapshot } from './types'

/** Deterministic demo seed — replace with imports from Server Actions / API later. */
export const DEMO_MASTER_SNAPSHOT: MasterSnapshot = {
  gpProfile: {
    id: 'gp-1',
    nameMr: 'रामोशी ग्रामपंचायत',
    nameEn: 'Ramoshi Gram Panchayat',
    gpCode: 'GP-MH-DEMO-001',
    districtMr: 'पुणे',
    talukaMr: 'हवेली',
    panchayatSamitiMr: 'हवेली पंचायत समिती',
    sarpanchNameMr: 'सुनीता जाधव',
    sarpanchMobile: '9876543210',
    gramSevakNameMr: 'श्री. खंडेराव पाटील',
    gramSevakMobile: '9876501234',
    addressMr: 'ग्रामपंचायत कार्यालय, रामोशी — ४११०४२',
  },
  financialYears: [
    {
      id: 'fy-2024-25',
      labelMr: '२०२४-२५',
      labelEn: '2024-25',
      startDate: '2024-04-01',
      endDate: '2025-03-31',
      status: 'closed',
    },
    {
      id: 'fy-2025-26',
      labelMr: '२०२५-२६',
      labelEn: '2025-26',
      startDate: '2025-04-01',
      endDate: '2026-03-31',
      status: 'active',
    },
  ],
  assessmentYears: [
    {
      id: 'ay-2025-26',
      labelMr: '२०२५-२६',
      labelEn: '2025-26',
      resolutionNumber: 'जा.क्र. १२/२०२५',
      resolutionDate: '2025-04-15',
      status: 'active',
    },
  ],
  accountHeads: [
    {
      id: 'ah-1',
      code: '१०१',
      descriptionMr: 'कर वसुली — घरपट्टी',
      descriptionEn: 'Tax collection — house tax',
      category: 'income',
      subCategory: 'tax',
    },
    {
      id: 'ah-2',
      code: '२०५',
      descriptionMr: 'वेतन — स्थापना',
      descriptionEn: 'Salary — establishment',
      category: 'expenditure',
      subCategory: 'establishment',
    },
    {
      id: 'ah-3',
      code: '३०७',
      descriptionMr: 'लघु दुरुस्त्या',
      descriptionEn: 'Minor works',
      category: 'expenditure',
      subCategory: 'maintenance',
    },
  ],
  bankAccounts: [
    {
      id: 'bk-1',
      bankNameMr: 'महाराष्ट्र बँक',
      branchMr: 'हवेली शाखा',
      accountNumber: '••••१२३४',
      ifsc: 'MAHB0001234',
      accountType: 'current',
    },
  ],
  citizens: [
    {
      id: 'c-1',
      nameMr: 'रामदास पाटील',
      nameEn: 'Ramdas Patil',
      aadhaarLast4: '९०१२',
      mobile: '9123456789',
      wardNumber: '३',
      addressMr: 'सर्वे नं. १४२/२, रामोशी',
      householdId: 'hh-1',
    },
    {
      id: 'c-2',
      nameMr: 'सुनीता जाधव',
      mobile: '9234567890',
      wardNumber: '१',
      addressMr: 'सर्वे नं. ८८/१, रामोशी',
      householdId: 'hh-2',
    },
    {
      id: 'c-3',
      nameMr: 'गणेश कुलकर्णी',
      mobile: '9345678901',
      wardNumber: '२',
      addressMr: 'सर्वे नं. १५/३, रामोशी',
    },
  ],
  electedMembers: [
    {
      id: 'em-1',
      nameMr: 'सुनीता जाधव',
      wardNumber: '—',
      role: 'sarpanch',
      electionDate: '2022-12-20',
      tenureEndDate: '2027-12-19',
      mobile: '9876543210',
    },
    {
      id: 'em-2',
      nameMr: 'अनिल भोसले',
      wardNumber: '२',
      role: 'upa_sarpanch',
      electionDate: '2022-12-20',
      tenureEndDate: '2027-12-19',
      mobile: '9876543211',
    },
    {
      id: 'em-3',
      nameMr: 'विद्या शिंदे',
      wardNumber: '४',
      role: 'ward_member',
      electionDate: '2022-12-20',
      tenureEndDate: '2027-12-19',
      mobile: '9876543212',
    },
  ],
}
